### ISSUE TITLE
difference between three dots, hamburger, and tabular listing icon?

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador-design#12]
I'm unclear on the difference between the three dots vs. the hamburger menu in particular and same icon appears to decorate the same window but obviously has different functionality.  The tabular display icon is also a little bit close in appearance to the hamburger menu icon.

**Comment by ggeisler** [comment]
Icons currently shown in the mockups are placeholders; we'll definitely be thinking harder about final icons.
