### ISSUE TITLE
keyboard and mouse controls?

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador-design#13]
I might have missed it in the videos and mock-ups, but will keyboard shortcuts be supported?  The designs don't really address zooming and panning yet, but I assume there will be keyboard and mouse support in those modes as well?

**Comment by ggeisler** [comment]
@beaudet You didn't miss it in the mockups because that's detail we haven't got to yet, but yes, we definitely intend for Mirador 3 to have solid accessibility support, including keyboard support.
