### ISSUE TITLE
Authentication and Authorization

### ISSUE THREAD

**Issue by christopher-johnson** [ProjectMirador/mirador-design#19]
Not clear how workspaces or annotations can be done without authentication.  I do not think that it is practical to allow anonymous persistence of state or annotations.  Provisioning sign in and a profile should be considered in the base design of the UI, even if authentication might be part of a Mirador ++ full featured package as an optional component.

**Comment by azaroth42** [comment]
We also need IIIF Authentication API support for restricted archival content. This was a major blocker for us with Mirador 2.0.

**Comment by damooo** [comment]
is it considered in development of Mirador 3?

**Comment by ggeisler** [comment]
@damooo If you haven't seen it, there is some work on authentication in Mirador 3 happening now:

- https://github.com/ProjectMirador/mirador/pull/2367
- https://github.com/ProjectMirador/mirador/issues/2636

and some related tickets.

**Comment by damooo** [comment]
@ggeisler Yes. thanks a lot.

**Comment by mejackreed** [comment]
IIIF Authentication v1.0 has been implemented and released in Mirador 3. Closing this issue for now. Please reopen or add new issues if there are remaining concerns about IIIF Authentication.
