### ISSUE TITLE
Options for moving windows around

### ISSUE THREAD

**Issue by emmastanford** [ProjectMirador/mirador-design#22]
Will it be possible to drag windows/albums to different positions within the workspace, or will they be stuck in the order they were loaded in? I can imagine wanting to drag two windows together for side-by-side comparison, and I think that should be made as easy as possible. I can also imagine users wanting to resize windows relative to each other, rather than simply zooming in on one at a time.

**Comment by ggeisler** [comment]
Yes, the user will be able to freely move windows around the workspace, place windows side-by-side (that is a primary use case), and resize windows.

If you watch the [Workspace window management video](https://stanford.box.com/s/ufx70lhthuvgn0faa870i9varqralfkx), at about 1 minute in you'll see that Window 6 is offset from the other windows, which is an example of how the user could move windows around the workspace. 

We weren't focused on this level of detail in the first round of mockups, but the plain gray boxes representing windows in the workspace mockup will actually have a title bar and affordances for resizing, etc.
