### ISSUE TITLE
Overlay with transparency (?) accessibility issues

### ISSUE THREAD

**Issue by mikeapp** [ProjectMirador/mirador-design#4]
In the first video/mocks, the menu drop-down from the hamburger appears to be semi transparent.  I'd be cautious about this due to legibility/accessibility.  

<img width="267" alt="screen shot 2018-09-24 at 4 07 59 pm" src="https://user-images.githubusercontent.com/1987952/45976198-15a7d680-c014-11e8-81bb-946172ec1c7f.png">

**Comment by ggeisler** [comment]
Yep, we're not 100% sure we'll keep this drop-down menu idea, but if we do, we'll definitely keep the legibility issue in mind.
